version: "2"
services:
  digit-wpdb:
    image: mariadb
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  digit-wp:
    image: wordpress
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    links:
      - digit-wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: password
